defaults:
  - _self_

num_envs: 1
freq: 40 # can only be divisible by 200
camera_follow: True
# Default to the obstacle course so Nav2 has interesting geometry.
env_name: obstacle-dense
# Examples: obstacle-[sparse|medium|dense], warehouse, warehouse-forklifts, hospital, office, grid

sensor:
  enable_lidar: True
  # RTX LiDAR config used by `IsaacSensorCreateRtxLidar`.
  # - `Example_Rotary_2D` gives a full 360° 2D scan (recommended for Nav2/SLAM).
  # - `HESAI_XT32_SD10` is a solid-state style sensor with limited coverage.
  lidar_config: Example_Rotary_2D
  enable_camera: True
  color_image: True
  depth_image: True
  semantic_segmentation: True

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False
