pointcloud_to_laserscan:
  ros__parameters:
    use_sim_time: True
    # Use the lidar frame so height filtering is relative to the sensor plane.
    # The PointCloud2 is already published in this frame.
    target_frame: unitree_go2/lidar_frame
    transform_tolerance: 0.2
    # Keep points near the lidar plane; drop ground/ceiling returns.
    min_height: -0.5
    max_height: 0.5
    angle_min: -3.14159
    angle_max: 3.14159
    angle_increment: 0.0087   # ~0.5 deg
    scan_time: 0.1
    range_min: 0.1
    range_max: 30.0
    use_inf: True
    inf_epsilon: 1.0
    # Shift scan timestamps slightly into the past to avoid TF lookup extrapolation errors.
    stamp_offset: 0.02
    # Downsample to keep slam_toolbox + costmaps from dropping messages due to full queues.
    max_pub_rate: 5.0
